# Generated by Django 4.1.7 on 2023-02-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='make',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='year',
            new_name='inventory_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='title',
        ),
    ]
